typesense: /bin/typesense-server --config=./typesense/typesense-config.ini
datasette: timeout 10m -s 9 datasette -i ./orchard.db -i ./status.db -i ./combined.db --cors --setting base_url /datasette/ -h 0.0.0.0 -p 5100
caddy: caddy run --config ./caddy/Caddyfile
