typesense: /bin/typesense-server --config=./typesense-config.ini
datasette: datasette -i ./orchard.db -i ./status.db -i ./combined.db --cors --setting base_url /datasette/ -h 0.0.0.0 -p 5100
caddy: caddy run
